import Head from "next/head";
import Image from "next/image";
import Form from "../components/Form";
import PublicApi from "../components/PublicApi";
import styles from "../styles/Home.module.css";

export default function Home() {
  const logoImg = { imgPath: "/images/logo.jpeg", imgAlt: "atmo logo" };

  return (
    <div>
      <Head>
        <title>Atmo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="sm:pl-20 smUp:px-40">
          <Image
            src={logoImg.imgPath}
            height={150}
            width={175.8}
            alt={logoImg.imgAlt}
          />
        </div>
        <div className="sm:pl-20">
          <Form />
        </div>
        <PublicApi />
      </div>
    </div>
  );
}
